name: fluttex
description: "A browser for Web X written in Flutter and Dart"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  common:
    path: packages/common

  smith:
    path: packages/smith

  flavio:
    path: packages/flavio

  bob:
    path: packages/bob

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
