name: fluttex
description: "A browser for Web X written in Flutter and Dart"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  html: ^0.15.4
  xml: ^6.5.0

  html_parser:
    path: packages/html_parser

  css_parser:
    path: packages/css_parser

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
