name: flavio

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common

  smith:
    path: ../smith

  http: ^1.2.1

  html_parser:
    path: ../html_parser
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
