name: flavio

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common

  smith:
    path: ../smith

  http: ^1.3.0

  html_parser:
    path: ../html_parser

  css_parser:
    path: ../css_parser

  http_parser: ^4.1.2
  syntax_highlight: ^0.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/assets/grammars/
