name: common

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  event_bus: ^2.0.1
  http: ^1.3.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
